# Gate 服务配置
Logger:
  service_name: "gate"
  environment: "dev"
  log_level: "info"
  console: true
  file: true
  file_path: "./logs/gate"
  file_name: "gate.log"
  max_size: 100
  max_age: 30
  max_backups: 10
  compress: true
  enable_caller: true
  enable_stacktrace: true

  Etcd:
    hosts: [ "192.168.6.54:2379" ]
    projectPrefix: "/wsh/moba"
    serverPrefix: "servers"
    commonPrefix: "common"
    masterPrefix: "master"
    friendPrefix: "friend"
    roomPrefix: "room"
    user:
    pass:
    certFile:
    certKeyFile:
    caCertFile:
    id:
    insecureSkipVerify:

DB:
  server:
    driver: "postgres"
    host: "192.168.6.54"
    port: 5432
    username: "root"
    password: "123321"
    maxIdleConns: 1
    maxOpenConns: 1

Servers:
  - name: "gate"
    configPath: "./excel"
    logPath: "./logs/gate"
    ip: "192.168.6.3" ## 本机内网ip
    port: 30999